### ISSUE TITLE
Dynamic DNS

### ISSUE THREAD

**Issue by christianh814** [alberttwong/archi_cloudnative#5]
You can further expand this by adding a Traffic Manager in the mix (Dynamic DNS). This will help by having the `*.apps.example.com` domain "fail over" to the warm standby for you.

There are a lot of offerings but these are the popular ones.

https://f5.com/products/modules/global-traffic-manager
https://dyn.com/traffic-director/

**Comment by alberttwong** [comment]
That's only when you're on prem right?   In AWS, ELB does that for you.

**Comment by christianh814** [comment]
Ah I didn't know that the ELB can switch you from, for example, us-west-1 to us-east1.

But yes, for on-prem you'd need a traffic manager.

**Comment by alberttwong** [comment]
ELB does zone failover so it doesn't move across AWS regions.   In fact, I don't know of any AWS service that can failover to another AWS region.
