### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by ericis** [alberttwong/archi_cloudnative#7]
I have multi-factor authentication enabled for GitHub, which might cause problems for Archi's beta Collaboration plug-in...

But, I tried:
- Importing with username/password: it began cloning and then silently stopped (failed)
- Importing with username/developer personal token: it began cloning and then silently stopped (failed)
- Cloning with `git`, but no `.archimate` file is provided

*Using Archi `v4.2.0`

**Comment by alberttwong** [comment]
Hi Eric, I'm not the author of the plugin.  You might want to contact https://github.com/archimatetool/archi-modelrepository-plugin

**Comment by ericis** [comment]
Thanks @alberttwong. I was guessing it would be an issue with the plug-in, but figured I'd comment here.
