### ISSUE TITLE
Error on import in Archi 4.6

### ISSUE THREAD

**Issue by dopo70** [alberttwong/archi_cloudnative#8]
![image](https://user-images.githubusercontent.com/61232176/74830205-e97cac00-5312-11ea-84da-4880c0d28c92.png)

![image](https://user-images.githubusercontent.com/61232176/74830255-04e7b700-5313-11ea-93dd-b6d80bad74ae.png)

**Comment by alberttwong** [comment]
I tried to load my project with a brand new installation and it worked.  Can you check.

**Comment by dopo70** [comment]
Hi Albert, I retried and the same error occurs. No problem, I'll create the objects manually then. Thanks for the effort anyway.
